[package]
name = "rhotic-txt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.28.6"
softbuffer = "0.3.0"
image = "0.24.6"
zerocopy = "0.6.1"
enum-iterator = "1.4.1"
rusttype = "0.9.3"
